name: /bin/cat
description: Enjoy it while it lasts, because it never does.
meta_description: "Enjoy it while it lasts, because it never does."

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: ""
plugins: [jekyll-paginate]

excerpt_separator: <!--more-->

# Details for the RSS feed generator
url: ""
author: "Peter Pan"
