name: 小兎宰治IcingTomato
description: 人生苦短，及时行乐
meta_description: "人生苦短，及时行乐"

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
paginate_path: "/page:num"
baseurl: ""
plugins: [jekyll-paginate]

excerpt_separator: <!--more-->

# Details for the RSS feed generator
url: "icing.fun"
author: "小兎宰治IcingTomato"
