name: Welcome to Whisper
description: Hello from Whisper
meta_description: "Enjoy it while it lasts, because it never does."

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
paginate_path: "/page:num"
baseurl: "/whisper"
plugins: [jekyll-paginate]

excerpt_separator: <!--more-->

# Details for the RSS feed generator
url: ""
author: "Icing Tomato"
