name: 小兎宰治IcingTomato
description: Everything Programmable.
meta_description: "Everything Programmable."

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
paginate_path: "/page:num"
baseurl: ""
plugins: [jekyll-paginate]

excerpt_separator: <!--more-->

# Details for the RSS feed generator
url: "icing.fun"
author: "小兎宰治IcingTomato"
